rails/test_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'blog_posts#index'
  match '/hello/:id', to: 'home#hello', via: :get

  resources :blog_posts
end

rails/test_project/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.role == 'admin'
      can :manage, ::BlogPost
    else
      can :read, ::BlogPost
      can [:update, :delete], ::BlogPost, user_id: user&.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

rails/test_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/test_project/app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates :title, :text, presence: true
end

rails/test_project/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog_post
end

rails/test_project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :email, presence: true
  validates :email, uniqueness: true

  has_many :blog_posts

  def blog_posts_count
    self.blog_posts.count
  end
end

rails/test_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  self.page_cache_directory = -> { ::Rails.root.join('public', 'cached_pages') }
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] || 'en'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

rails/test_project/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  caches_page :index

  def index
    @blog_posts = ::BlogPost.joins(:user)
                            .accessible_by(current_ability)
                            .select('blog_posts.*', 'users.name AS user_name')
  end

  def new
    @blog_post = ::BlogPost.new
  end

  def create
    @blog_post = ::BlogPost.new
    @blog_post.attributes = blog_post_params
    @blog_post.user_id = current_user.id
    success = @blog_post.save
    redirect_to blog_posts_path
  end

  def edit
    @blog_post = ::BlogPost.find params[:id]
  end

  def update
    @blog_post = ::BlogPost.find params[:id]
    @success = @blog_post.update_attributes(blog_post_params)
    respond_to do |format|
      format.html do
        redirect_to blog_posts_path
      end
      format.js do
        if @success
          @blog_posts = ::BlogPost.all
        else
          @blog_post.errors.add('title', 'Another error')
          logger.info "Blog post errors: #{@blog_post.errors.full_messages}"
        end
      end
    end
  end

  def destroy
    @blog_post = ::BlogPost.find params[:id]
    authorize!(:delete, @blog_post)
    @blog_post.destroy
    redirect_to blog_posts_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :text)
  end
end

rails/test_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    ::Rails.logger.info 'Index method called'
    render json: {a: 1, b: 2}
  end

  def hello
    @user = ::User.find params[:id]
  end
end

rails/test_project/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/test_project/app/views/blog_posts/_errors.html.erb
<% if @blog_post.errors[field_name].present? %>
  <div class="alert alert-danger">
    <%= @blog_post.errors[field_name].join(', ') %>
  </div>
<% end %>

rails/test_project/app/views/blog_posts/_form.html.erb
<div class="row">
  <div class="col-md-8 blog-post-form">
    <%= form_for(@blog_post, remote: true) do |f| %>
      <div class="form-group <%= 'has-error' if @blog_post.errors['title'].present? %>">
        <label for="blog_post_title"><%= t('ui.blog_posts.title') %>:</label>
        <%= f.text_field :title, class: "form-control" %>
        <%= render partial: 'errors', locals: {field_name: 'title'} %>
      </div>
      <div class="form-group <%= 'has-error' if @blog_post.errors['text'].present? %>">
        <label for="blog_post_title"><%= t('ui.blog_posts.text') %>:</label>
        <%= f.text_area :text, class: "form-control" %>
        <%= render partial: 'errors', locals: {field_name: 'text'} %>
      </div>
      <div><%= f.submit submit_label, class: 'btn btn-danger' %></div>
    <% end %>
  </div>
</div>

rails/test_project/app/views/blog_posts/edit.html.erb
<h1 id="edit_header">Edit Blog Post "<%= @blog_post.title %>"</h1>
<div class="content">
  <%= render partial: 'form', locals: {submit_label: 'Update'} %>
</div>

rails/test_project/app/views/blog_posts/index.html.erb
<h1>Blog posts <small>list</small></h1>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
    <th>Actions</th>
  </tr>
  <% @blog_posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= post.user_name %></td>
      <td>
        <%= link_to 'Edit', edit_blog_post_path(post), class: 'btn btn-success'  if can?(:update, post) %>
        <%= link_to 'Delete',
          blog_post_path(post),
          method: 'delete', 
          class: 'btn btn-danger',
          'data-confirm' => 'Are you sure?'
        %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add new', new_blog_post_path, class: 'btn btn-primary' %>

rails/test_project/app/views/blog_posts/new.html.erb
<h2>New Blog Post</h2>
<%= render partial: 'form', locals: {submit_label: 'Create'} %>

rails/test_project/app/views/blog_posts/update.js.erb
<% if @success %>
  $('.content').html('<%=j render template: '/blog_posts/index' %>');
<% else %>
  $('.content').html('<%=j render partial: '/blog_posts/form', locals: {submit_label: 'Update'} %>');
<% end %>

rails/test_project/app/views/home/hello.html.erb
<h1>Hello!</h1>
<b><%= @user.name %></b>

rails/test_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render partial: '/shared/logged_in_status' unless devise_controller? %>
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key == 'alert' ? 'danger' : 'success' %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

rails/test_project/app/views/shared/_logged_in_status.html.erb
<div class="logged-in-status">
  <% if user_signed_in? %>
    Logged in as <%= current_user.name %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', new_user_session_path %>
  <% end %>
</div>